<?php
/**
 * Dashboard language system — DE (default) / EN
 * Usage: t('key')  →  translated string
 * Switch: ?setlang=en  or  ?setlang=de
 */

function dashboardSetLang(string $lang): void {
    $allowed = ['de', 'en'];
    if (in_array($lang, $allowed, true)) {
        $_SESSION['fh_lang'] = $lang;
    }
}

function dashboardLang(): string {
    return $_SESSION['fh_lang'] ?? 'de';
}

function t(string $key): string {
    static $strings = null;
    if ($strings === null) {
        $strings = [
            'de' => [
                // Navbar
                'nav.online'         => 'Online',
                'nav.notifications'  => 'Benachrichtigungen',
                'nav.mark_read'      => 'Gelesen',
                'nav.show_all'       => 'Alle anzeigen →',
                'nav.no_activity'    => 'Keine neuen Aktivitäten',
                'nav.no_filter'      => 'Keine Ereignisse in diesem Filter',
                'nav.logout'         => 'Abmelden',
                'nav.normal_view'    => 'Normale Ansicht',
                'nav.admin_mode'     => 'Admin-Modus',
                'nav.lang_label'     => 'EN',
                'nav.lang_next'      => 'en',
                'nav.lang_title'     => 'Switch to English',
                // JS time strings
                'time.just_now'      => 'gerade eben',
                'time.ago_prefix'    => 'vor ',
                'time.sec_suffix'    => 's',
                'time.min_suffix'    => 'm',
                'time.hour_suffix'   => 'h',
                'time.day_suffix'    => 'd',
                'notif.unread'       => 'ungelesen · ',
                'notif.total'        => 'gesamt',
                // Upgrade banner
                'upgrade.title'      => 'Kostenlos-Tarif',
                'upgrade.sub'        => '— Mehr Panels, Live Activity &amp; Insights mit Premium',
                'upgrade.cta'        => '💎 Upgrade ansehen',
                'upgrade.close'      => 'Schließen',
                // Sidebar
                'sidebar.search'     => 'Suche',
                'sidebar.pinned'     => 'Angepinnt',
                'sidebar.nav_admin'  => 'Arbeitsbereich',
                'sidebar.nav_user'   => 'Navigation',
                'sidebar.legal'      => 'Rechtliches',
                // Footer
                'footer.copyright'   => '© 2026 Fahrstuhl Bot',
                'footer.help'        => 'Hilfe?',
                'footer.help_title'  => 'Brauchst du Hilfe? Komm in den Support-Discord!',

                // ── Gemeinsame UI-Bausteine (seitenübergreifend) ──────────
                'common.save'            => 'Speichern',
                'common.save_settings'   => 'Einstellungen speichern',
                'common.cancel'          => 'Abbrechen',
                'common.unsaved'         => 'Ungespeicherte Änderungen',
                'common.ready'           => 'Bereit',
                'common.saving'          => 'Speichert …',
                'common.saved'           => 'Gespeichert ✓',
                'common.error'           => 'Fehler',
                'common.active'          => 'Aktiv',
                'common.inactive'        => 'Inaktiv',
                'common.limit_reached'   => 'Limit erreicht',
                'common.enable_module'   => 'Modul aktivieren',
                'common.optional'        => 'optional',

                // ── Leveling ──────────────────────────────────────────────
                'lvl.eyebrow'            => 'Engagement-Modul',
                'lvl.subtitle'           => 'XP, Belohnungen und Anti-Farm-Regeln an einem Ort.',
                'lvl.disabled_title'     => 'Leveling ist deaktiviert',
                'lvl.disabled_text'      => 'Aktiviere zuerst das Modul, danach kannst du XP, Voice-XP und Anti-Farm-Regeln einstellen.',
                'lvl.xp_settings'        => 'XP-Einstellungen',
                'lvl.min_xp'             => 'Min. XP',
                'lvl.max_xp'             => 'Max. XP',
                'lvl.cooldown'           => 'Abklingzeit (Sekunden)',
                'lvl.announcement'       => 'Ankündigung',
                'lvl.send_levelup'       => 'Level-Up-Nachrichten senden',
                'lvl.announce_channel'   => 'Ankündigungs-Kanal',
                'lvl.use_msg_channel'    => 'Kanal der Nachricht verwenden',
                'lvl.levelup_msg'        => 'Level-Up-Nachricht',
                'lvl.levelup_hint'       => 'Leer lassen für den Standardtext. Platzhalter: {user}, {level}.',
                'lvl.antifarm'           => 'Anti-Farm',
                'lvl.min_msg_len'        => 'Mindestlänge einer Nachricht',
                'lvl.min_msg_hint'       => 'Kürzere Nachrichten geben keine XP.',
                'lvl.block_dupes'        => 'Doppelte Nachrichten blocken (3× dieselbe in 60s → keine XP)',
                'lvl.voice_xp'           => 'Voice-XP',
                'lvl.voice_enable'       => 'Voice-XP aktivieren',
                'lvl.voice_per_min'      => 'Voice-XP pro Minute',
                'lvl.voice_hint'         => 'XP pro Minute im Sprachkanal (ab 2 Mitgliedern, nicht stummgeschaltet).',
                'lvl.live_test'          => 'Live-Test',
                'lvl.test_amount'        => 'Test-XP-Menge',
                'lvl.test_hint'          => 'Vergibt Test-XP an deinen eigenen Dashboard-Account.',
                'lvl.test_btn'           => '+XP testen',
                'lvl.role_rewards'       => 'Rollen-Belohnungen',
                'lvl.reward_mode'        => 'Belohnungs-Modus',
                'lvl.mode_stack'         => 'Sammeln (alle behalten)',
                'lvl.mode_highest'       => 'Nur höchste (alte entfernen)',
                'lvl.role_placeholder'   => '– Rolle –',
                'lvl.channel_placeholder'=> '– Kanal –',
                'lvl.rewards_used'       => 'Belohnungen genutzt',
                'lvl.add_reward'         => 'Belohnung hinzufügen',
                'lvl.advanced'           => 'Erweitert · Ausnahmen',
                'lvl.ignored_roles'      => 'Ignorierte Rollen',
                'lvl.ignored_channels'   => 'Ignorierte Kanäle',
                'lvl.noxp_hint'          => 'In diesen Kanälen gibt es nie XP.',
                'lvl.multipliers'        => 'XP-Multiplikatoren',
                'lvl.role_multipliers'   => 'Rollen-Multiplikatoren',
                'lvl.add_role_mult'      => 'Rollen-Multiplikator hinzufügen',
                'lvl.channel_multipliers'=> 'Kanal-Multiplikatoren',
                'lvl.add_channel_mult'   => 'Kanal-Multiplikator hinzufügen',
                'lvl.bulk_actions'       => 'Sammelaktionen',
                'lvl.autocreate'         => 'Rollen automatisch anlegen',
                'lvl.xp_reset'           => 'XP zurücksetzen',
                'lvl.reset_user_ph'      => 'User-ID für XP-Reset',
                'lvl.reset_user_btn'     => 'XP dieses Users zurücksetzen',
                'lvl.reset_user_alert'   => 'Bitte gib eine User-ID ein.',
                'lvl.reset_all_btn'      => 'Alle Server-XP zurücksetzen',
                'lvl.reset_all_confirm'  => 'Wirklich alle XP-Daten dieses Servers zurücksetzen? Das lässt sich nicht rückgängig machen.',
                'lvl.save_hint'          => 'Die Leveling-Konfiguration wird direkt gespeichert.',
                'lvl.leaderboard'        => 'Globale Rangliste',
                'lvl.members_tracked'    => 'Mitglieder erfasst',
                'lvl.th_rank'            => 'Platz',
                'lvl.th_user'            => 'Mitglied',
                'lvl.th_level'           => 'Level',
                'lvl.th_progress'        => 'Fortschritt',
                'lvl.th_xp'              => 'XP',
                'lvl.ac_levels'          => 'Level mit Komma getrennt',
                'lvl.ac_prefix'          => 'Rollen-Präfix',
                'lvl.ac_create'          => 'Rollen anlegen',

                // ── Tickets ───────────────────────────────────────────────
                'tk.eyebrow'          => 'Support-Modul',
                'tk.subtitle'         => 'Panel, Zuweisung und Team-Ablauf an einem Ort.',
                'tk.disabled_title'   => 'Ticket-Modul ist deaktiviert',
                'tk.panel_design'     => 'Panel-Gestaltung',
                'tk.panel_title'      => 'Panel-Überschrift',
                'tk.panel_desc'       => 'Panel-Beschreibung',
                'tk.button_label'     => 'Button-Text',
                'tk.panel_info'       => 'Panel-Infos',
                'tk.info_extra'       => 'Zusätzliche Panel-Infos anzeigen',
                'tk.info_open'        => 'Offene Tickets',
                'tk.info_avg'         => 'Ø Lösungszeit',
                'tk.info_overdue'     => 'Überfällige Tickets',
                'tk.info_updated'     => 'Letzte Aktualisierung',
                'tk.info_hint'        => 'Wenn deaktiviert, bleibt das Panel exakt wie bisher.',
                'tk.tech_setup'       => 'Technische Einrichtung',
                'tk.logs_hint_pre'    => 'Ticket-Protokolle werden zentral unter',
                'tk.logs_hint_post'   => ' gesteuert. Der Transkript-Kanal ist nur für die Archivdateien.',
                'tk.category'         => 'Ticket-Kategorie',
                'tk.category_new'     => '– Neue Kategorie anlegen –',
                'tk.staff_role'       => 'Team-Rolle',
                'tk.staff_none'       => '– Keine Team-Rolle –',
                'tk.staff_hint'       => 'Rolle, die alle Tickets sehen und verwalten darf.',
                'tk.high_role'        => 'Leitungs-Rolle',
                'tk.high_none'        => '– Keine Leitungs-Rolle –',
                'tk.high_hint'        => 'Erweiterte Rechte — kann Aktionen des Teams überschreiben.',
                'tk.transcript'       => 'Transkript-Kanal',
                'tk.transcript_none'  => '– Keine Transkripte –',
                'tk.transcript_hint'  => 'Hier landen die Archivdateien beim Schließen eines Tickets.',
                'tk.priority'         => 'Standard-Priorität',
                'tk.close_delay'      => 'Verzögerung beim Schließen (Sekunden)',
                'tk.sla'              => 'SLA-Minuten',
                'tk.sla_hint'         => 'Ältere Tickets gelten als überfällig. 0 schaltet das ab.',
                'tk.types'            => 'Ticket-Typen',
                'tk.types_hint'       => 'Max. 5 Typen. Leere Bezeichnungen werden ignoriert.',
                'tk.deployment'       => 'Veröffentlichung',
                'tk.target_channel'   => 'Ziel-Kanal',
                'tk.select_channel'   => '– Kanal wählen –',
                'tk.resend_hint'      => 'Erneutes Senden bearbeitet das bestehende Panel.',
                'tk.panel_limit'      => 'Ticket-Panel-Limit erreicht',
                'tk.live_preview'     => 'Live-Vorschau',
                'tk.instructions'     => 'Hinweise',
                'tk.live_test'        => 'Live-Test',
                'tk.test_reason'      => 'Test-Grund',
                'tk.analytics'        => 'Ticket-Auswertung',
                'tk.a_open'           => 'Offen',
                'tk.a_claimed'        => 'Übernommen',
                'tk.a_resolved'       => 'Gelöste Tickets',
                'tk.a_avg'            => 'Ø Lösungszeit (Min.)',
                'tk.a_overdue'        => 'SLA überschritten',
                'tk.a_fb_count'       => 'Rückmeldungen',
                'tk.a_fb_avg'         => 'Ø Bewertung',
                'tk.top_claimers'     => 'Aktivstes Team',
                'tk.archive'          => 'Geschlossene Tickets',
                'tk.archive_hint'     => 'Das Archiv füllt sich, sobald Tickets geöffnet oder geschlossen werden.',
                'tk.empty'            => 'Leer',
                'tk.save_hint'        => 'Die Grundeinstellungen werden direkt gespeichert.',
                'tk.no_access'        => 'Kein Zugriff auf ',
                'tk.prio_high'        => 'Hoch',

                // ── Moderation-Übersicht ──────────────────────────────────
                'mh.title'            => 'Moderation',
                'mh.subtitle'         => 'Moderations-Werkzeuge für Server, die du besitzt oder verwaltest.',
                'mh.last_refresh'     => 'Zuletzt aktualisiert:',
                'mh.your_servers'     => 'Deine Server',
                'mh.your_servers_sub' => 'mit Moderationszugriff',
                'mh.warnings'         => 'Verwarnungen',
                'mh.warnings_sub'     => 'Verlauf pro Server',
                'mh.timeouts'         => 'Timeouts',
                'mh.timeouts_sub'     => 'braucht Bot-Berechtigung',
                'mh.notes'            => 'Mod-Notizen',
                'mh.notes_sub'        => 'interner Verlauf',
                'mh.ready'            => 'Bereit',
                'mh.console'          => 'Moderations-Konsole',
                'mh.console_sub'      => 'Verwarnungen, Notizen, Timeouts und Nutzer-Verlauf verwalten.',
                'mh.logs'             => 'Laufzeit-Protokolle',
                'mh.logs_sub'         => 'Live-Logs des Bots für Moderations- und Rechte-Probleme.',
                'mh.automod'          => 'AutoMod',
                'mh.automod_sub'      => 'Filter, Schutzregeln und automatische Aktionen.',
                'mh.events'           => 'Discord-Ereignisse',
                'mh.events_sub'       => 'Welche Server-Ereignisse in welchem Kanal protokolliert werden.',
                'mh.soon'             => 'Bald',
                'mh.coming'           => 'In Arbeit',
                'mh.esc_rules'        => 'Eskalations-Regeln',
                'mh.esc_rules_sub'    => 'Wiederholte Verwarnungen automatisch zu Zeitstrafen hochstufen.',
                'mh.case_page'        => 'Fall-Übersicht beim Mitglied',
                'mh.case_page_sub'    => 'Kompakter Fallverlauf direkt auf der Mitglieder-Seite.',
                'mh.mod_cmds'         => 'Mod-Befehle',
                'mh.mod_cmds_sub'     => 'Slash-Befehle für Verwarnung/Notiz/Timeout direkt aus Discord.',
                'mh.no_access_title'  => 'Noch kein Moderationszugriff',
                'mh.no_access_text'   => 'Du musst Server-Inhaber sein, in Discord die Rechte „Administrator“ oder „Server verwalten“ haben, oder die eingestellte Fahrstuhl-Dashboard-Admin-Rolle besitzen.',

                // ── AutoMod ───────────────────────────────────────────────
                'am.eyebrow'        => 'Moderations-Modul',
                'am.disabled_title' => 'AutoMod ist deaktiviert',
                'am.quick_preset'   => 'Schnell-Vorlage',
                'am.p_relaxed'      => 'Locker',
                'am.p_balanced'     => 'Ausgewogen',
                'am.p_strict'       => 'Streng',
                'am.rules'          => 'Schutzregeln',
                'am.hits24'         => 'Treffer (24 h)',
                'am.users'          => 'Mitglieder',
                'am.total'          => 'Gesamt',
                'am.a_global'       => 'Globale Einstellung',
                'am.a_none'         => 'Nichts tun',
                'am.a_delete'       => 'Löschen',
                'am.a_warn'         => 'Verwarnen',
                'am.a_timeout'      => 'Timeout',
                'am.a_kick'         => 'Kicken',
                'am.a_ban'          => 'Bannen',
                'am.r_invites'      => 'Einladungen',
                'am.r_invites_sub'  => 'Blockiert Discord-Einladungslinks und Vanity-URLs.',
                'am.r_links'        => 'Links',
                'am.r_links_sub'    => 'Blockiert externe Links, die nicht freigegeben sind.',
                'am.r_spam'         => 'Spam',
                'am.r_spam_sub'     => 'Erkennt Nachrichtenfluten in kurzer Zeit.',
                'am.r_repeat'       => 'Wiederholter Text',
                'am.r_repeat_sub'   => 'Blockiert immer wieder kopierte Textblöcke.',
                'am.r_mentions'     => 'Massen-Erwähnungen',
                'am.r_mentions_sub' => 'Stoppt Ping-Wellen und Massen-Erwähnungen.',
                'am.r_caps'         => 'Großbuchstaben',
                'am.r_caps_sub'     => 'Stoppt Schreien mit zu vielen Großbuchstaben.',
                'am.thresholds'     => 'Schwellenwerte',
                'am.mention_limit'  => 'Erwähnungs-Limit',
                'am.spam_window'    => 'Spam-Zeitfenster (s)',
                'am.dupe_count'     => 'Anzahl Wiederholungen',
                'am.caps_percent'   => 'Großbuchstaben-Anteil (%)',
                'am.caps_minlen'    => 'Mindestlänge für Caps-Prüfung',
                'am.punishment'     => 'Bestrafung',
                'am.mode'           => 'Modus',
                'am.mode_fixed'     => 'Fest (immer dieselbe)',
                'am.mode_escalate'  => 'Steigernd (Verwarnung → Timeout → Kick)',
                'am.action'         => 'Aktion',
                'am.at_strikes'     => 'Ab wie vielen Verstößen',
                'am.timeout_min'    => 'Timeout-Dauer (Minuten)',
                'am.filter_detail'  => 'Filter-Details',
                'am.delete_msg'     => 'Nachricht löschen',
                'am.delete_msg_sub' => 'Blockierte Nachrichten automatisch entfernen',
                'am.warn_user'      => 'Mitglied verwarnen',
                'am.warn_user_sub'  => 'Kurze Verwarnung im Kanal senden',
                'am.blocked_terms'  => 'Gesperrte Begriffe (einer pro Zeile)',
                'am.blocked_action' => 'Aktion bei gesperrten Begriffen',
                'am.blocked_hint'   => 'Wird ausgeführt, wenn gesperrte Begriffe oder Regex-Muster greifen.',
                'am.whitelist'      => 'Erlaubte Links (einer pro Zeile)',
                'am.whitelist_hint' => 'Links mit diesen Wörtern werden nicht blockiert.',
                'am.warn_message'   => 'Verwarnungs-Text',
                'am.ignored_roles'  => 'Ignorierte Rollen',
                'am.ignored_chans'  => 'Ignorierte Kanäle',
                'am.exempt_admins'  => 'Admins ausnehmen',
                'am.exempt_sub'     => 'Admins werden von AutoMod nicht erfasst',
                'am.live_test'      => 'Live-Test',
                'am.test_message'   => 'Testnachricht',
                'am.no_access'      => 'Kein Zugriff auf ',

                // ── Server-Einstellungen ──────────────────────────────────
                'sc.eyebrow'        => 'Server-Werkzeuge',
                'sc.subtitle'       => 'Zentrale Server-Einstellungen: Rollen, Dashboard-Zugriff, Health-Checks und direkte Sprünge in die wichtigsten Bereiche.',
                'sc.setup_progress' => 'Einrichtungs-Fortschritt',
                'sc.setup_sub'      => 'Grundeinstellungen für einen sauber laufenden Server.',
                'sc.server_roles'   => 'Server-Rollen',
                'sc.admin_role'     => 'Admin-Rolle',
                'sc.troll_role'     => 'Troll-Rolle',
                'sc.automove_role'  => 'Auto-Move-Rolle',
                'sc.select_role'    => 'Rolle wählen',
                'sc.not_set'        => 'Nicht gesetzt',
                'sc.no_restriction' => 'Keine Einschränkung',
                'sc.save_role'      => 'Rolle speichern',
                'sc.no_roles'       => 'Die Rollenliste ist gerade nicht über die API verfügbar.',
                'sc.dash_access'    => 'Dashboard-Zugriff',
                'sc.dash_save'      => 'Dashboard-Zugriff speichern',
                'sc.quick_actions'  => 'Schnellzugriff',
                'sc.quick_sub'      => 'Direkte Sprünge in die wichtigsten Konfigurationsseiten.',
                'sc.bot_health'     => 'Bot-Zustand',
                'sc.bot_health_sub' => 'Rechte-Prüfung für diesen Server.',
                'sc.trolls_sub'     => 'Aktuell laufende Troll-Aktionen auf diesem Server.',
                'sc.trolls_none'    => 'Gerade laufen keine Troll-Aktionen.',
                'sc.server_info'    => 'Server-Infos',
                'sc.server_info_sub'=> 'Discord-Basisdaten.',

                // ── Moderations-Konsole ───────────────────────────────────
                'mo.case'           => 'Fall',
                'mo.case_details'   => 'Fall-Details',
                'mo.case_history'   => 'Fall-Verlauf',
                'mo.case_id'        => 'Fall-Nr.',
                'mo.created'        => 'Erstellt',
                'mo.updated'        => 'Geändert',
                'mo.details'        => 'Details',
                'mo.duration'       => 'Dauer',
                'mo.edit_reason'    => 'Grund bearbeiten',
                'mo.guild'          => 'Server',
                'mo.moderator'      => 'Moderator',
                'mo.reason'         => 'Grund',
                'mo.resolve'        => 'Erledigen / Wieder öffnen',
                'mo.resolved_page'  => 'Auf dieser Seite erledigt',
                'mo.status'         => 'Status',
                'mo.time'           => 'Zeit',
                'mo.timeouts'       => 'Timeouts',
                'mo.total_cases'    => 'Fälle gesamt',
                'mo.type'           => 'Typ',
                'mo.user'           => 'Mitglied',
                'mo.warns'          => 'Verwarnungen',
                'mo.all_status'     => 'Alle Status',
                'mo.all_types'      => 'Alle Typen',
                'mo.open'           => 'Offen',
                'mo.resolved'       => 'Erledigt',
                'mo.page'           => 'Seite',
                'mo.apply_hint'     => 'Wendet einen Fall auf eine Discord-User-ID an. Halte die Gründe kurz und sachlich.',
                'mo.none_selected'  => 'Noch kein Fall ausgewählt. Nutze „Öffnen“ in der Fall-Tabelle.',
                'mo.filter_hint'    => 'Mit den Filtern findest du schnell den richtigen Fall und kannst ihn bearbeiten.',
                'mo.d_none'         => 'Keine Nachrichten löschen',
                'mo.d_hour'         => 'Letzte Stunde löschen',
                'mo.d_day'          => 'Letzten Tag löschen',
                'mo.d_week'         => 'Letzte 7 Tage löschen',
                'mo.t_10min'        => '10 Minuten',
                'mo.t_1hour'        => '1 Stunde',
                'mo.t_6hours'       => '6 Stunden',
                'mo.t_1day'         => '1 Tag',
                'mo.t_7days'        => '7 Tage',
                'mo.t_28days'       => '28 Tage',

                // ── Statistiken / Analytics ───────────────────────────────
                'st.title'          => 'Server-Auswertung',
                'st.health_snap'    => 'Zustand auf einen Blick',
                'st.advanced'       => 'Erweiterte Auswertung (Pro)',
                'st.advanced_locked'=> '🔒 Erweiterte Auswertung ist Pro',
                'st.top_mod'        => 'Häufigste Moderationsarten',
                'st.health_sum'     => 'Zusammenfassung Serverzustand',
                'st.activity'       => 'Aktivitätsverlauf',
                'st.top_lists'      => 'Bestenlisten',
                'st.quick_read'     => 'Kurz erklärt',

                // ── Social Alerts ─────────────────────────────────────────
                'so.announce_ch'    => 'Ankündigungs-Kanal',
                'so.preview'        => 'Vorschau',
                'so.free_plan'      => 'Kostenlos-Tarif',
                'so.t_youtube'      => 'YouTube',
                'so.t_twitch'       => 'Twitch Live',
                'so.t_rss'          => 'RSS',

                // ── Temp Voice ────────────────────────────────────────────
                'tv.hub'            => 'Join-Hub-Sprachkanal',
                'tv.user_limit'     => 'Nutzer-Limit',
                'tv.preview'        => 'Live-Vorschau',

                // ── Logging ───────────────────────────────────────────────
                'lg.log_channel'    => 'Protokoll-Kanal',
                'lg.select_channel' => '– Kanal wählen –',
                'lg.fallback_global'=> '— globalen Kanal verwenden —',
                'lg.override_ch'    => 'Abweichender Kanal',
                'lg.fallback_group' => '— Gruppen-/Standardkanal verwenden —',

                // ── Reaction Roles ────────────────────────────────────────
                'rr.display_mode'   => 'Darstellung',
                'rr.mode_buttons'   => 'Buttons (empfohlen)',
                'rr.mode_dropdown'  => 'Auswahlmenü',
                'rr.choose_channel' => '– Kanal wählen –',
                'rr.no_role'        => '– Keine Rolle –',
                'rr.embed_title'    => 'Embed-Titel',
                'rr.embed_desc'     => 'Embed-Beschreibung',
                'rr.author_text'    => 'Author-Text',
                'rr.footer_text'    => 'Footer-Text',
                'rr.preview'        => 'Live-Vorschau',
                'rr.target_ch'      => 'Ziel-Kanal',
                'rr.panel_ch'       => 'Panel-Kanal',
                'common.none'       => 'Keine',
                'mo.duration_lbl'   => 'Dauer:',
                'mo.no_reason'      => 'Kein Grund angegeben',
            ],
            'en' => [
                // Navbar
                'nav.online'         => 'Online',
                'nav.notifications'  => 'Notifications',
                'nav.mark_read'      => 'Mark read',
                'nav.show_all'       => 'Show all →',
                'nav.no_activity'    => 'No new activity',
                'nav.no_filter'      => 'No events in this filter',
                'nav.logout'         => 'Logout',
                'nav.normal_view'    => 'Normal View',
                'nav.admin_mode'     => 'Admin Mode',
                'nav.lang_label'     => 'DE',
                'nav.lang_next'      => 'de',
                'nav.lang_title'     => 'Zu Deutsch wechseln',
                // JS time strings
                'time.just_now'      => 'just now',
                'time.ago_prefix'    => '',
                'time.sec_suffix'    => 's ago',
                'time.min_suffix'    => 'm ago',
                'time.hour_suffix'   => 'h ago',
                'time.day_suffix'    => 'd ago',
                'notif.unread'       => 'unread · ',
                'notif.total'        => 'total',
                // Upgrade banner
                'upgrade.title'      => 'Free Plan',
                'upgrade.sub'        => '— More panels, live activity &amp; insights with Premium',
                'upgrade.cta'        => '💎 View upgrade',
                'upgrade.close'      => 'Close',
                // Sidebar
                'sidebar.search'     => 'Search',
                'sidebar.pinned'     => 'Pinned',
                'sidebar.nav_admin'  => 'Workspace',
                'sidebar.nav_user'   => 'Navigation',
                'sidebar.legal'      => 'Legal',
                // Footer
                'footer.copyright'   => '© 2026 Fahrstuhl Bot',
                'footer.help'        => 'Help?',
                'footer.help_title'  => 'Need help? Join our Support Discord!',

                // ── Shared UI building blocks ─────────────────────────────
                'common.save'            => 'Save',
                'common.save_settings'   => 'Save Settings',
                'common.cancel'          => 'Cancel',
                'common.unsaved'         => 'Unsaved changes',
                'common.ready'           => 'Ready',
                'common.saving'          => 'Saving …',
                'common.saved'           => 'Saved ✓',
                'common.error'           => 'Error',
                'common.active'          => 'Active',
                'common.inactive'        => 'Inactive',
                'common.limit_reached'   => 'Limit reached',
                'common.enable_module'   => 'Enable module',
                'common.optional'        => 'optional',

                // ── Leveling ──────────────────────────────────────────────
                'lvl.eyebrow'            => 'Engagement Module',
                'lvl.subtitle'           => 'XP, rewards and anti-farm rules in one place.',
                'lvl.disabled_title'     => 'Leveling is disabled',
                'lvl.disabled_text'      => 'Enable the module first, then set up XP, voice XP and anti-farm rules.',
                'lvl.xp_settings'        => 'XP Settings',
                'lvl.min_xp'             => 'Min XP',
                'lvl.max_xp'             => 'Max XP',
                'lvl.cooldown'           => 'Cooldown (seconds)',
                'lvl.announcement'       => 'Announcement',
                'lvl.send_levelup'       => 'Send level-up messages',
                'lvl.announce_channel'   => 'Announcement channel',
                'lvl.use_msg_channel'    => 'Use message channel',
                'lvl.levelup_msg'        => 'Level-up message',
                'lvl.levelup_hint'       => 'Leave empty for default. Use {user}, {level}.',
                'lvl.antifarm'           => 'Anti-Farm',
                'lvl.min_msg_len'        => 'Min message length',
                'lvl.min_msg_hint'       => 'Messages shorter than this gain no XP.',
                'lvl.block_dupes'        => 'Block duplicate messages (3+ same in 60s → no XP)',
                'lvl.voice_xp'           => 'Voice XP',
                'lvl.voice_enable'       => 'Enable voice XP',
                'lvl.voice_per_min'      => 'Voice XP per minute',
                'lvl.voice_hint'         => 'XP per minute in voice (2+ members, not muted).',
                'lvl.live_test'          => 'Live test',
                'lvl.test_amount'        => 'Test XP amount',
                'lvl.test_hint'          => 'Grants test XP to your own dashboard account.',
                'lvl.test_btn'           => 'Test +XP',
                'lvl.role_rewards'       => 'Role Rewards',
                'lvl.reward_mode'        => 'Reward mode',
                'lvl.mode_stack'         => 'Stack roles (keep all)',
                'lvl.mode_highest'       => 'Highest only (remove old)',
                'lvl.role_placeholder'   => '– Role –',
                'lvl.channel_placeholder'=> '– Channel –',
                'lvl.rewards_used'       => 'rewards used',
                'lvl.add_reward'         => 'Add reward',
                'lvl.advanced'           => 'Advanced · Bypasses',
                'lvl.ignored_roles'      => 'Ignored roles',
                'lvl.ignored_channels'   => 'Ignored channels',
                'lvl.noxp_hint'          => 'No-XP channels never grant XP.',
                'lvl.multipliers'        => 'XP multipliers',
                'lvl.role_multipliers'   => 'Role multipliers',
                'lvl.add_role_mult'      => 'Add role multiplier',
                'lvl.channel_multipliers'=> 'Channel multipliers',
                'lvl.add_channel_mult'   => 'Add channel multiplier',
                'lvl.bulk_actions'       => 'Bulk actions',
                'lvl.autocreate'         => 'Auto-create roles',
                'lvl.xp_reset'           => 'XP reset',
                'lvl.reset_user_ph'      => 'User ID for XP reset',
                'lvl.reset_user_btn'     => 'Reset this user\'s XP',
                'lvl.reset_user_alert'   => 'Please enter a user ID.',
                'lvl.reset_all_btn'      => 'Reset all server XP',
                'lvl.reset_all_confirm'  => 'Reset all XP data for this server? This cannot be undone.',
                'lvl.save_hint'          => 'The leveling configuration is saved directly.',
                'lvl.leaderboard'        => 'Global Leaderboard',
                'lvl.members_tracked'    => 'members tracked',
                'lvl.th_rank'            => 'Rank',
                'lvl.th_user'            => 'User',
                'lvl.th_level'           => 'Level',
                'lvl.th_progress'        => 'Progress',
                'lvl.th_xp'              => 'XP',
                'lvl.ac_levels'          => 'Comma separated levels',
                'lvl.ac_prefix'          => 'Role prefix',
                'lvl.ac_create'          => 'Create roles',

                // ── Tickets ───────────────────────────────────────────────
                'tk.eyebrow'          => 'Support Module',
                'tk.subtitle'         => 'Panel, routing and team workflow in one place.',
                'tk.disabled_title'   => 'Ticket module is disabled',
                'tk.panel_design'     => 'Panel Design',
                'tk.panel_title'      => 'Panel title',
                'tk.panel_desc'       => 'Panel description',
                'tk.button_label'     => 'Button label',
                'tk.panel_info'       => 'Panel info',
                'tk.info_extra'       => 'Show additional panel info',
                'tk.info_open'        => 'Open tickets',
                'tk.info_avg'         => 'Avg resolution',
                'tk.info_overdue'     => 'Overdue tickets',
                'tk.info_updated'     => 'Last updated',
                'tk.info_hint'        => 'When off, the panel stays exactly as before.',
                'tk.tech_setup'       => 'Technical Setup',
                'tk.logs_hint_pre'    => 'Ticket activity logs are controlled centrally in',
                'tk.logs_hint_post'   => '. The transcript channel is only for ticket archive files.',
                'tk.category'         => 'Ticket category',
                'tk.category_new'     => '– Create new category –',
                'tk.staff_role'       => 'Staff role',
                'tk.staff_none'       => '– No staff role –',
                'tk.staff_hint'       => 'Role that can see and manage all tickets.',
                'tk.high_role'        => 'High team role',
                'tk.high_none'        => '– No high team role –',
                'tk.high_hint'        => 'Elevated access — can override staff actions.',
                'tk.transcript'       => 'Transcript channel',
                'tk.transcript_none'  => '– No transcripts –',
                'tk.transcript_hint'  => 'Transcript archive files will be sent here upon closing.',
                'tk.priority'         => 'Default priority',
                'tk.close_delay'      => 'Close delay (seconds)',
                'tk.sla'              => 'SLA minutes',
                'tk.sla_hint'         => 'Tickets older than this are marked overdue. Use 0 to disable.',
                'tk.types'            => 'Ticket types',
                'tk.types_hint'       => 'Max. 5 types. Empty labels are ignored.',
                'tk.deployment'       => 'Deployment',
                'tk.target_channel'   => 'Target channel',
                'tk.select_channel'   => '– Select channel –',
                'tk.resend_hint'      => 'Sending again edits the existing panel.',
                'tk.panel_limit'      => 'Ticket panel limit reached',
                'tk.live_preview'     => 'Live Preview',
                'tk.instructions'     => 'Instructions',
                'tk.live_test'        => 'Live test',
                'tk.test_reason'      => 'Test reason',
                'tk.analytics'        => 'Ticket Analytics',
                'tk.a_open'           => 'Open',
                'tk.a_claimed'        => 'Claimed',
                'tk.a_resolved'       => 'Resolved tickets',
                'tk.a_avg'            => 'Avg resolution (min)',
                'tk.a_overdue'        => 'SLA overdue',
                'tk.a_fb_count'       => 'Feedback count',
                'tk.a_fb_avg'         => 'Feedback avg',
                'tk.top_claimers'     => 'Top claimers',
                'tk.archive'          => 'Closed archive',
                'tk.archive_hint'     => 'The archive fills up as tickets are opened or closed.',
                'tk.empty'            => 'Empty',
                'tk.save_hint'        => 'Base settings are saved directly.',
                'tk.no_access'        => 'No access to ',
                'tk.prio_high'        => 'High',

                // ── Moderation overview ───────────────────────────────────
                'mh.title'            => 'Moderation',
                'mh.subtitle'         => 'Moderation tools for servers you own or administrate.',
                'mh.last_refresh'     => 'Last refresh:',
                'mh.your_servers'     => 'Your servers',
                'mh.your_servers_sub' => 'moderation access',
                'mh.warnings'         => 'Warnings',
                'mh.warnings_sub'     => 'per server history',
                'mh.timeouts'         => 'Timeouts',
                'mh.timeouts_sub'     => 'needs bot permission',
                'mh.notes'            => 'Mod notes',
                'mh.notes_sub'        => 'internal history',
                'mh.ready'            => 'Ready',
                'mh.console'          => 'Moderation Console',
                'mh.console_sub'      => 'Manage warns, mod notes, timeouts and user history.',
                'mh.logs'             => 'Runtime Logs',
                'mh.logs_sub'         => 'Live bot logs for debugging moderation and permission issues.',
                'mh.automod'          => 'AutoMod',
                'mh.automod_sub'      => 'Filters, protection rules and automatic actions.',
                'mh.events'           => 'Discord Events',
                'mh.events_sub'       => 'Which server events are logged to which channel.',
                'mh.soon'             => 'Soon',
                'mh.coming'           => 'Coming Soon',
                'mh.esc_rules'        => 'Escalation Rules',
                'mh.esc_rules_sub'    => 'Auto-escalate repeated warnings into timed actions.',
                'mh.case_page'        => 'Member Case Page',
                'mh.case_page_sub'    => 'Compact case history directly on each user detail page.',
                'mh.mod_cmds'         => 'Mod Commands',
                'mh.mod_cmds_sub'     => 'Slash commands for warn/note/timeout directly from Discord.',
                'mh.no_access_title'  => 'No moderation access yet',
                'mh.no_access_text'   => 'You need to be the server owner, have Discord Administrator/Manage Server permission, or have the configured Fahrstuhl Dashboard Admin Role.',

                // ── AutoMod ───────────────────────────────────────────────
                'am.eyebrow'        => 'Moderation Module',
                'am.disabled_title' => 'AutoMod is disabled',
                'am.quick_preset'   => 'Quick Preset',
                'am.p_relaxed'      => 'Relaxed',
                'am.p_balanced'     => 'Balanced',
                'am.p_strict'       => 'Strict',
                'am.rules'          => 'Security Rules',
                'am.hits24'         => '24h hits',
                'am.users'          => 'Users',
                'am.total'          => 'Total',
                'am.a_global'       => 'Use global',
                'am.a_none'         => 'None',
                'am.a_delete'       => 'Delete',
                'am.a_warn'         => 'Warn',
                'am.a_timeout'      => 'Timeout',
                'am.a_kick'         => 'Kick',
                'am.a_ban'          => 'Ban',
                'am.r_invites'      => 'Invites',
                'am.r_invites_sub'  => 'Blocks Discord invite links and vanity invite URLs.',
                'am.r_links'        => 'Links',
                'am.r_links_sub'    => 'Blocks non-whitelisted external links.',
                'am.r_spam'         => 'Spam',
                'am.r_spam_sub'     => 'Detects message floods in a short time window.',
                'am.r_repeat'       => 'Repeated text',
                'am.r_repeat_sub'   => 'Blocks repeated copy-paste spam chunks.',
                'am.r_mentions'     => 'Mass mentions',
                'am.r_mentions_sub' => 'Stops mention raids and mass pings.',
                'am.r_caps'         => 'Caps',
                'am.r_caps_sub'     => 'Stops shouting with too many uppercase letters.',
                'am.thresholds'     => 'Thresholds',
                'am.mention_limit'  => 'Mention limit',
                'am.spam_window'    => 'Spam window (s)',
                'am.dupe_count'     => 'Duplicate count',
                'am.caps_percent'   => 'Caps percent',
                'am.caps_minlen'    => 'Caps min length',
                'am.punishment'     => 'Punishment',
                'am.mode'           => 'Mode',
                'am.mode_fixed'     => 'Fixed (always the same)',
                'am.mode_escalate'  => 'Escalate (warn → timeout → kick)',
                'am.action'         => 'Action',
                'am.at_strikes'     => 'At strikes',
                'am.timeout_min'    => 'Timeout minutes',
                'am.filter_detail'  => 'Filter detail',
                'am.delete_msg'     => 'Delete message',
                'am.delete_msg_sub' => 'Remove blocked messages automatically',
                'am.warn_user'      => 'Warn user',
                'am.warn_user_sub'  => 'Send a short warning in the channel',
                'am.blocked_terms'  => 'Blocked terms (one per line)',
                'am.blocked_action' => 'Blocked terms action',
                'am.blocked_hint'   => 'Action used when blocked terms or regex terms match.',
                'am.whitelist'      => 'Link whitelist (one per line)',
                'am.whitelist_hint' => "Links containing these words won't be blocked.",
                'am.warn_message'   => 'Warn message',
                'am.ignored_roles'  => 'Ignored roles',
                'am.ignored_chans'  => 'Ignored channels',
                'am.exempt_admins'  => 'Exempt admins',
                'am.exempt_sub'     => 'Admins bypass AutoMod',
                'am.live_test'      => 'Live test',
                'am.test_message'   => 'Test message',
                'am.no_access'      => 'No access to ',

                // ── Server config ─────────────────────────────────────────
                'sc.eyebrow'        => 'Server Tools',
                'sc.subtitle'       => 'Central server settings: roles, dashboard access, health checks and shortcuts to the important areas.',
                'sc.setup_progress' => 'Setup Progress',
                'sc.setup_sub'      => 'Core settings needed for a clean server workflow.',
                'sc.server_roles'   => 'Server Roles',
                'sc.admin_role'     => 'Admin role',
                'sc.troll_role'     => 'Troll role',
                'sc.automove_role'  => 'Auto-move role',
                'sc.select_role'    => 'Select role',
                'sc.not_set'        => 'Not set',
                'sc.no_restriction' => 'No restriction',
                'sc.save_role'      => 'Save role',
                'sc.no_roles'       => 'Role list is not available from the API right now.',
                'sc.dash_access'    => 'Dashboard access',
                'sc.dash_save'      => 'Save dashboard access',
                'sc.quick_actions'  => 'Quick Actions',
                'sc.quick_sub'      => 'Shortcuts to the most important configuration pages.',
                'sc.bot_health'     => 'Bot Health',
                'sc.bot_health_sub' => 'Permission checks for the current server.',
                'sc.trolls_sub'     => 'Current running troll actions on this server.',
                'sc.trolls_none'    => 'No active troll actions right now.',
                'sc.server_info'    => 'Server Info',
                'sc.server_info_sub'=> 'Basic Discord metadata.',

                // ── Moderation console ────────────────────────────────────
                'mo.case'           => 'Case',
                'mo.case_details'   => 'Case Details',
                'mo.case_history'   => 'Case History',
                'mo.case_id'        => 'Case ID',
                'mo.created'        => 'Created',
                'mo.updated'        => 'Updated',
                'mo.details'        => 'Details',
                'mo.duration'       => 'Duration',
                'mo.edit_reason'    => 'Edit reason',
                'mo.guild'          => 'Guild',
                'mo.moderator'      => 'Moderator',
                'mo.reason'         => 'Reason',
                'mo.resolve'        => 'Resolve / Reopen',
                'mo.resolved_page'  => 'Resolved on page',
                'mo.status'         => 'Status',
                'mo.time'           => 'Time',
                'mo.timeouts'       => 'Timeouts',
                'mo.total_cases'    => 'Total cases',
                'mo.type'           => 'Type',
                'mo.user'           => 'User',
                'mo.warns'          => 'Warns',
                'mo.all_status'     => 'All status',
                'mo.all_types'      => 'All types',
                'mo.open'           => 'Open',
                'mo.resolved'       => 'Resolved',
                'mo.page'           => 'Page',
                'mo.apply_hint'     => 'Apply a case to one Discord user ID. Keep reasons short and factual.',
                'mo.none_selected'  => 'No case selected yet. Use the Open button in the case table.',
                'mo.filter_hint'    => 'Use filters to quickly find the right case and open details for edits.',
                'mo.d_none'         => 'Do not delete messages',
                'mo.d_hour'         => 'Delete last hour',
                'mo.d_day'          => 'Delete last day',
                'mo.d_week'         => 'Delete last 7 days',
                'mo.t_10min'        => '10 minutes',
                'mo.t_1hour'        => '1 hour',
                'mo.t_6hours'       => '6 hours',
                'mo.t_1day'         => '1 day',
                'mo.t_7days'        => '7 days',
                'mo.t_28days'       => '28 days',

                // ── Stats / Analytics ─────────────────────────────────────
                'st.title'          => 'Server Analytics',
                'st.health_snap'    => 'Server Health Snapshot',
                'st.advanced'       => 'Advanced Insights (Pro)',
                'st.advanced_locked'=> '🔒 Advanced Insights are Pro',
                'st.top_mod'        => 'Top Moderation Types',
                'st.health_sum'     => 'Server Health Summary',
                'st.activity'       => 'Activity Charts',
                'st.top_lists'      => 'Top Lists',
                'st.quick_read'     => 'Beginner Quick Read',

                // ── Social Alerts ─────────────────────────────────────────
                'so.announce_ch'    => 'Announcement channel',
                'so.preview'        => 'Preview',
                'so.free_plan'      => 'Free Plan',
                'so.t_youtube'      => 'YouTube',
                'so.t_twitch'       => 'Twitch Live',
                'so.t_rss'          => 'RSS',

                // ── Temp Voice ────────────────────────────────────────────
                'tv.hub'            => 'Join hub voice channel',
                'tv.user_limit'     => 'User limit',
                'tv.preview'        => 'Live preview',

                // ── Logging ───────────────────────────────────────────────
                'lg.log_channel'    => 'Log channel',
                'lg.select_channel' => '– Select channel –',
                'lg.fallback_global'=> '— fall back to global —',
                'lg.override_ch'    => 'Override channel',
                'lg.fallback_group' => '— use group/global fallback —',

                // ── Reaction Roles ────────────────────────────────────────
                'rr.display_mode'   => 'Display mode',
                'rr.mode_buttons'   => 'Buttons (recommended)',
                'rr.mode_dropdown'  => 'Dropdown menu',
                'rr.choose_channel' => '– Choose channel –',
                'rr.no_role'        => '– No role –',
                'rr.embed_title'    => 'Embed title',
                'rr.embed_desc'     => 'Embed description',
                'rr.author_text'    => 'Author text',
                'rr.footer_text'    => 'Footer text',
                'rr.preview'        => 'Live preview',
                'rr.target_ch'      => 'Target channel',
                'rr.panel_ch'       => 'Panel channel',
                'common.none'       => 'None',
                'mo.duration_lbl'   => 'Duration:',
                'mo.no_reason'      => 'No reason provided',
            ],
        ];
    }
    $lang = dashboardLang();
    return $strings[$lang][$key] ?? $strings['de'][$key] ?? $key;
}
