<?php
/**
 * Dashboard language system — DE (default) / EN
 * Usage: t('key')  →  translated string
 * Switch: ?setlang=en  or  ?setlang=de
 */

function dashboardSetLang(string $lang): void {
    $allowed = ['de', 'en'];
    if (in_array($lang, $allowed, true)) {
        $_SESSION['fh_lang'] = $lang;
    }
}

function dashboardLang(): string {
    return $_SESSION['fh_lang'] ?? 'de';
}

function t(string $key): string {
    static $strings = null;
    if ($strings === null) {
        $strings = [
            'de' => [
                // Navbar
                'nav.online'         => 'Online',
                'nav.notifications'  => 'Benachrichtigungen',
                'nav.mark_read'      => 'Gelesen',
                'nav.show_all'       => 'Alle anzeigen →',
                'nav.no_activity'    => 'Keine neuen Aktivitäten',
                'nav.no_filter'      => 'Keine Ereignisse in diesem Filter',
                'nav.logout'         => 'Abmelden',
                'nav.normal_view'    => 'Normal View',
                'nav.admin_mode'     => 'Admin Mode',
                'nav.lang_label'     => 'EN',
                'nav.lang_next'      => 'en',
                'nav.lang_title'     => 'Switch to English',
                // JS time strings
                'time.just_now'      => 'gerade eben',
                'time.ago_prefix'    => 'vor ',
                'time.sec_suffix'    => 's',
                'time.min_suffix'    => 'm',
                'time.hour_suffix'   => 'h',
                'time.day_suffix'    => 'd',
                'notif.unread'       => 'ungelesen · ',
                'notif.total'        => 'gesamt',
                // Upgrade banner
                'upgrade.title'      => 'Free Plan',
                'upgrade.sub'        => '— Mehr Panels, Live Activity &amp; Insights mit Premium',
                'upgrade.cta'        => '💎 Upgrade ansehen',
                'upgrade.close'      => 'Schließen',
                // Sidebar
                'sidebar.search'     => 'Suche',
                'sidebar.pinned'     => 'Angepinnt',
                'sidebar.nav_admin'  => 'Workspace',
                'sidebar.nav_user'   => 'Navigation',
                'sidebar.legal'      => 'Legal',
                // Footer
                'footer.copyright'   => '© 2026 Fahrstuhl Bot',
                'footer.help'        => 'Hilfe?',
                'footer.help_title'  => 'Brauchst du Hilfe? Komm in den Support-Discord!',

                // ── Gemeinsame UI-Bausteine (seitenübergreifend) ──────────
                'common.save'            => 'Speichern',
                'common.save_settings'   => 'Einstellungen speichern',
                'common.cancel'          => 'Abbrechen',
                'common.unsaved'         => 'Ungespeicherte Änderungen',
                'common.ready'           => 'Bereit',
                'common.saving'          => 'Speichert …',
                'common.saved'           => 'Gespeichert ✓',
                'common.error'           => 'Fehler',
                'common.active'          => 'Aktiv',
                'common.inactive'        => 'Inaktiv',
                'common.limit_reached'   => 'Limit erreicht',
                'common.enable_module'   => 'Modul aktivieren',
                'common.optional'        => 'optional',

                // ── Leveling ──────────────────────────────────────────────
                'lvl.eyebrow'            => 'Engagement-Modul',
                'lvl.subtitle'           => 'XP, Belohnungen und Anti-Farm-Regeln an einem Ort.',
                'lvl.disabled_title'     => 'Leveling ist deaktiviert',
                'lvl.disabled_text'      => 'Aktiviere zuerst das Modul, danach kannst du XP, Voice-XP und Anti-Farm-Regeln einstellen.',
                'lvl.xp_settings'        => 'XP-Einstellungen',
                'lvl.min_xp'             => 'Min. XP',
                'lvl.max_xp'             => 'Max. XP',
                'lvl.cooldown'           => 'Abklingzeit (Sekunden)',
                'lvl.announcement'       => 'Ankündigung',
                'lvl.send_levelup'       => 'Level-Up-Nachrichten senden',
                'lvl.announce_channel'   => 'Ankündigungs-Kanal',
                'lvl.use_msg_channel'    => 'Kanal der Nachricht verwenden',
                'lvl.levelup_msg'        => 'Level-Up-Nachricht',
                'lvl.levelup_hint'       => 'Leer lassen für den Standardtext. Platzhalter: {user}, {level}.',
                'lvl.antifarm'           => 'Anti-Farm',
                'lvl.min_msg_len'        => 'Mindestlänge einer Nachricht',
                'lvl.min_msg_hint'       => 'Kürzere Nachrichten geben keine XP.',
                'lvl.block_dupes'        => 'Doppelte Nachrichten blocken (3× dieselbe in 60s → keine XP)',
                'lvl.voice_xp'           => 'Voice-XP',
                'lvl.voice_enable'       => 'Voice-XP aktivieren',
                'lvl.voice_per_min'      => 'Voice-XP pro Minute',
                'lvl.voice_hint'         => 'XP pro Minute im Sprachkanal (ab 2 Mitgliedern, nicht stummgeschaltet).',
                'lvl.live_test'          => 'Live-Test',
                'lvl.test_amount'        => 'Test-XP-Menge',
                'lvl.test_hint'          => 'Vergibt Test-XP an deinen eigenen Dashboard-Account.',
                'lvl.test_btn'           => '+XP testen',
                'lvl.role_rewards'       => 'Rollen-Belohnungen',
                'lvl.reward_mode'        => 'Belohnungs-Modus',
                'lvl.mode_stack'         => 'Sammeln (alle behalten)',
                'lvl.mode_highest'       => 'Nur höchste (alte entfernen)',
                'lvl.role_placeholder'   => '– Rolle –',
                'lvl.channel_placeholder'=> '– Kanal –',
                'lvl.rewards_used'       => 'Belohnungen genutzt',
                'lvl.add_reward'         => 'Belohnung hinzufügen',
                'lvl.advanced'           => 'Erweitert · Ausnahmen',
                'lvl.ignored_roles'      => 'Ignorierte Rollen',
                'lvl.ignored_channels'   => 'Ignorierte Kanäle',
                'lvl.noxp_hint'          => 'In diesen Kanälen gibt es nie XP.',
                'lvl.multipliers'        => 'XP-Multiplikatoren',
                'lvl.role_multipliers'   => 'Rollen-Multiplikatoren',
                'lvl.add_role_mult'      => 'Rollen-Multiplikator hinzufügen',
                'lvl.channel_multipliers'=> 'Kanal-Multiplikatoren',
                'lvl.add_channel_mult'   => 'Kanal-Multiplikator hinzufügen',
                'lvl.bulk_actions'       => 'Sammelaktionen',
                'lvl.autocreate'         => 'Rollen automatisch anlegen',
                'lvl.xp_reset'           => 'XP zurücksetzen',
                'lvl.reset_user_ph'      => 'User-ID für XP-Reset',
                'lvl.reset_user_btn'     => 'XP dieses Users zurücksetzen',
                'lvl.reset_user_alert'   => 'Bitte gib eine User-ID ein.',
                'lvl.reset_all_btn'      => 'Alle Server-XP zurücksetzen',
                'lvl.reset_all_confirm'  => 'Wirklich alle XP-Daten dieses Servers zurücksetzen? Das lässt sich nicht rückgängig machen.',
                'lvl.save_hint'          => 'Die Leveling-Konfiguration wird direkt gespeichert.',
                'lvl.leaderboard'        => 'Globale Rangliste',
                'lvl.members_tracked'    => 'Mitglieder erfasst',
                'lvl.th_rank'            => 'Platz',
                'lvl.th_user'            => 'Mitglied',
                'lvl.th_level'           => 'Level',
                'lvl.th_progress'        => 'Fortschritt',
                'lvl.th_xp'              => 'XP',
                'lvl.ac_levels'          => 'Level mit Komma getrennt',
                'lvl.ac_prefix'          => 'Rollen-Präfix',
                'lvl.ac_create'          => 'Rollen anlegen',
            ],
            'en' => [
                // Navbar
                'nav.online'         => 'Online',
                'nav.notifications'  => 'Notifications',
                'nav.mark_read'      => 'Mark read',
                'nav.show_all'       => 'Show all →',
                'nav.no_activity'    => 'No new activity',
                'nav.no_filter'      => 'No events in this filter',
                'nav.logout'         => 'Logout',
                'nav.normal_view'    => 'Normal View',
                'nav.admin_mode'     => 'Admin Mode',
                'nav.lang_label'     => 'DE',
                'nav.lang_next'      => 'de',
                'nav.lang_title'     => 'Zu Deutsch wechseln',
                // JS time strings
                'time.just_now'      => 'just now',
                'time.ago_prefix'    => '',
                'time.sec_suffix'    => 's ago',
                'time.min_suffix'    => 'm ago',
                'time.hour_suffix'   => 'h ago',
                'time.day_suffix'    => 'd ago',
                'notif.unread'       => 'unread · ',
                'notif.total'        => 'total',
                // Upgrade banner
                'upgrade.title'      => 'Free Plan',
                'upgrade.sub'        => '— More panels, live activity &amp; insights with Premium',
                'upgrade.cta'        => '💎 View upgrade',
                'upgrade.close'      => 'Close',
                // Sidebar
                'sidebar.search'     => 'Search',
                'sidebar.pinned'     => 'Pinned',
                'sidebar.nav_admin'  => 'Workspace',
                'sidebar.nav_user'   => 'Navigation',
                'sidebar.legal'      => 'Legal',
                // Footer
                'footer.copyright'   => '© 2026 Fahrstuhl Bot',
                'footer.help'        => 'Help?',
                'footer.help_title'  => 'Need help? Join our Support Discord!',

                // ── Shared UI building blocks ─────────────────────────────
                'common.save'            => 'Save',
                'common.save_settings'   => 'Save Settings',
                'common.cancel'          => 'Cancel',
                'common.unsaved'         => 'Unsaved changes',
                'common.ready'           => 'Ready',
                'common.saving'          => 'Saving …',
                'common.saved'           => 'Saved ✓',
                'common.error'           => 'Error',
                'common.active'          => 'Active',
                'common.inactive'        => 'Inactive',
                'common.limit_reached'   => 'Limit reached',
                'common.enable_module'   => 'Enable module',
                'common.optional'        => 'optional',

                // ── Leveling ──────────────────────────────────────────────
                'lvl.eyebrow'            => 'Engagement Module',
                'lvl.subtitle'           => 'XP, rewards and anti-farm rules in one place.',
                'lvl.disabled_title'     => 'Leveling is disabled',
                'lvl.disabled_text'      => 'Enable the module first, then set up XP, voice XP and anti-farm rules.',
                'lvl.xp_settings'        => 'XP Settings',
                'lvl.min_xp'             => 'Min XP',
                'lvl.max_xp'             => 'Max XP',
                'lvl.cooldown'           => 'Cooldown (seconds)',
                'lvl.announcement'       => 'Announcement',
                'lvl.send_levelup'       => 'Send level-up messages',
                'lvl.announce_channel'   => 'Announcement channel',
                'lvl.use_msg_channel'    => 'Use message channel',
                'lvl.levelup_msg'        => 'Level-up message',
                'lvl.levelup_hint'       => 'Leave empty for default. Use {user}, {level}.',
                'lvl.antifarm'           => 'Anti-Farm',
                'lvl.min_msg_len'        => 'Min message length',
                'lvl.min_msg_hint'       => 'Messages shorter than this gain no XP.',
                'lvl.block_dupes'        => 'Block duplicate messages (3+ same in 60s → no XP)',
                'lvl.voice_xp'           => 'Voice XP',
                'lvl.voice_enable'       => 'Enable voice XP',
                'lvl.voice_per_min'      => 'Voice XP per minute',
                'lvl.voice_hint'         => 'XP per minute in voice (2+ members, not muted).',
                'lvl.live_test'          => 'Live test',
                'lvl.test_amount'        => 'Test XP amount',
                'lvl.test_hint'          => 'Grants test XP to your own dashboard account.',
                'lvl.test_btn'           => 'Test +XP',
                'lvl.role_rewards'       => 'Role Rewards',
                'lvl.reward_mode'        => 'Reward mode',
                'lvl.mode_stack'         => 'Stack roles (keep all)',
                'lvl.mode_highest'       => 'Highest only (remove old)',
                'lvl.role_placeholder'   => '– Role –',
                'lvl.channel_placeholder'=> '– Channel –',
                'lvl.rewards_used'       => 'rewards used',
                'lvl.add_reward'         => 'Add reward',
                'lvl.advanced'           => 'Advanced · Bypasses',
                'lvl.ignored_roles'      => 'Ignored roles',
                'lvl.ignored_channels'   => 'Ignored channels',
                'lvl.noxp_hint'          => 'No-XP channels never grant XP.',
                'lvl.multipliers'        => 'XP multipliers',
                'lvl.role_multipliers'   => 'Role multipliers',
                'lvl.add_role_mult'      => 'Add role multiplier',
                'lvl.channel_multipliers'=> 'Channel multipliers',
                'lvl.add_channel_mult'   => 'Add channel multiplier',
                'lvl.bulk_actions'       => 'Bulk actions',
                'lvl.autocreate'         => 'Auto-create roles',
                'lvl.xp_reset'           => 'XP reset',
                'lvl.reset_user_ph'      => 'User ID for XP reset',
                'lvl.reset_user_btn'     => 'Reset this user\'s XP',
                'lvl.reset_user_alert'   => 'Please enter a user ID.',
                'lvl.reset_all_btn'      => 'Reset all server XP',
                'lvl.reset_all_confirm'  => 'Reset all XP data for this server? This cannot be undone.',
                'lvl.save_hint'          => 'The leveling configuration is saved directly.',
                'lvl.leaderboard'        => 'Global Leaderboard',
                'lvl.members_tracked'    => 'members tracked',
                'lvl.th_rank'            => 'Rank',
                'lvl.th_user'            => 'User',
                'lvl.th_level'           => 'Level',
                'lvl.th_progress'        => 'Progress',
                'lvl.th_xp'              => 'XP',
                'lvl.ac_levels'          => 'Comma separated levels',
                'lvl.ac_prefix'          => 'Role prefix',
                'lvl.ac_create'          => 'Create roles',
            ],
        ];
    }
    $lang = dashboardLang();
    return $strings[$lang][$key] ?? $strings['de'][$key] ?? $key;
}
